setwd("C:/Users/school/Dropbox/Cousera/Exploratory Data Analysis/project1")
x<-"exdata-data-household_power_consumption/household_power_consumption.txt"
install.packages("lubridate")
library(lubridate)
file<-read.table(x,header = T, sep = ";", stringsAsFactor = F)
data<-subset(file,Date == "1/2/2007")
data1<-subset(file,Date == "2/2/2007")
info<-rbind(data,data1)
date<-as.Date(info$Date, format = "%d/%m/%Y")
datetime<-ymd_hms(paste(date,info$Time, sep = "_"))
active<-as.numeric(as.character(info$Global_active_power))
a<-as.numeric(info$Sub_metering_1)
b<-as.numeric(info$Sub_metering_2)
c<-as.numeric(info$Sub_metering_3)
global<-as.numeric(info$Global_reactive_power)
voltage<-as.numeric(info$Voltage)
png(file = "plot4.png", width = 480, height = 480)
par(mfcol = c(2, 2), mar = c(4, 4, 4, 2), oma = c(1, 1, 0, 0))
plot(datetime,active,ylab = "Global Active Power (Kilowatts)",xlab = "", type = "l", pch = ".")
plot(datetime,a,ylab = "Energy Sub Meeting",xlab = "", type = "l", pch = ".")
lines(b~datetime,type = "l", pch = ".", col="red")
lines(c~datetime,type = "l", pch = ".", col="blue")
legend(lwd=2,"topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black", "red", "blue"),pt.cex=1,cex=0.8)
plot(datetime,voltage,ylab = "Voltage",xlab = "datetime", type = "l", pch = ".")
plot(datetime,global,ylab = "Global_reactive_power",xlab = "datetime", type = "l", pch = ".")
dev.off()
