setwd("C:/Users/school/Dropbox/Cousera/Exploratory Data Analysis/project1")
x<-"exdata-data-household_power_consumption/household_power_consumption.txt"
install.packages("lubridate")
library(lubridate)
file<-read.table(x,header = T, sep = ";", stringsAsFactor = F)[,c(1,2,7,8,9)]
data<-subset(file,Date == "1/2/2007")
data1<-subset(file,Date == "2/2/2007")
info<-rbind(data,data1)
a<-as.numeric(info$Sub_metering_1)
b<-as.numeric(info$Sub_metering_2)
c<-as.numeric(info$Sub_metering_3)
date<-as.Date(info$Date, format = "%d/%m/%Y")
datetime<-ymd_hms(paste(date,info$Time, sep = "_"))
png(file = "plot3.png", width = 480, height = 480)
plot(datetime,a,ylab = "Energy Sub Meeting",xlab = "", type = "l", pch = ".")
lines(b~datetime,type = "l", pch = ".", col="red")
lines(c~datetime,type = "l", pch = ".", col="blue")
legend(lwd=2,"topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black", "red", "blue"))
dev.off()